services:

  backend_test:
    container_name: backend_test
    build:
      context: ./backend
      dockerfile: Dockerfile_backend_test
    volumes:
      - ./backend:/backend
    environment:
      ES_PORT: 9200
      ES_DATABASE: es_test
    networks:
      - web_test_app_network
    ports:
      - '127.0.0.1:8000:8000'
    command: sh -c "while ! nc -z es_test 9200; do sleep 1; done && python db/elasticsearch/migrations.py && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: es_test
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - web_test_app_network
    ports:
      - "127.0.0.1:9200:9200"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.11.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es_test:9200
    networks:
      - web_test_app_network
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

networks:
  web_test_app_network:
    driver: bridge