services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile_backend_test
    volumes:
      - ./backend:/backend
    env_file:
      - /backend/.env
    networks:
      - web_app_network
    ports:
      - '127.0.0.1:8000:8000'
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    volumes:
      - data_es_db:/usr/share/elasticsearch/data
    networks:
      - web_app_network
    ports:
      - "127.0.0.1:9200:9200"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.11.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    networks:
      - web_app_network
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

networks:
  web_app_network:
    driver: bridge

volumes:
  data_es_db: