services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile_backend
    volumes:
      - ./backend:/backend
    env_file:
      - /backend/.env
    networks:
      - web_app_network
    ports:
      - '127.0.0.1:8000:8000'
    command: sh -c "python db/elasticsearch/migrations.py && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    healthcheck:
      test: curl -s http://es:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    volumes:
      - data_es_db:/usr/share/elasticsearch/data
    networks:
      - web_app_network
    ports:
      - "127.0.0.1:9200:9200"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.11.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    networks:
      - web_app_network
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - web_app_network
    depends_on:
      - backend

  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      volumes:
        - grafana-data:/var/lib/grafana
        - grafana-config:/etc/grafana
      ports:
        - "3000:3000"
      depends_on:
        - prometheus
      restart: always
      networks:
        - web_app_network
      user: "0"


networks:
  web_app_network:
    driver: bridge

volumes:
  data_es_db:
  grafana-data:
  grafana-config:
  prometheus-data:
