name: Python Application Test

on:
  push:
    branches: [ main, backend/** ]
  pull_request:
    branches: [ main, backend/** ]

jobs:
    test_job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Lint with flake8
          run: |
            pip install flake8
            # stop the build if there are Python syntax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Cache Docker images.
          uses: ScribeMD/docker-cache@0.3.6
          with:
            key: docker-${{ runner.os }}-${{ hashFiles('docker-compose-test.yaml') }}
        - name: Docker compose up
          run: |
            docker compose -f docker-compose-test.yaml up -d &&
            docker compose -f docker-compose-test.yaml run --rm backend_test sh -c 'pytest'
